version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: edumentorDB
      POSTGRES_USER: server
      POSTGRES_PASSWORD: edumentor123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/edumentorDB
      SPRING_DATASOURCE_USERNAME: server
      SPRING_DATASOURCE_PASSWORD: edumentor123

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - app
volumes:
  postgres_data: